(local ffi (require :ffi))
(local buffer (require :string.buffer))

(local f (io.open "zeno.c" "wb"))
(f:write "/* NOTE: THIS FILE WAS GENERATED BY \"zeno.fnl\". */\n\nint main(void) { return 0; }\n")
(f:close)
